# Camera Estimation
geo_calib:
    # set to None to download from default url
    model_path:

# Depth Estimation
midas:
    model_path: "Intel/dpt-hybrid-midas"

depth_anything_v2:
    model_path: "depth-anything/Depth-Anything-V2-Large-hf"

depth_pro:
    # set to None to download from default url
    model_path:

lotus_depth:
    model_path: "jingheya/lotus-depth-g-v1-0"

# Normal Estimation
lotus_normal:
    model_path: "jingheya/lotus-normal-g-v1-0"

dsine:
    # set to None to download from default url
    model_path:
    efficientnet_path:

# Segmentation
upernet:
    model_path: openmmlab/upernet-convnext-large

# Reconstruction
dust3r:
    model_path: "nielsr/DUSt3R_ViTLarge_BaseDecoder_512_dpt"

moge:
    model_path: "Ruicheng/moge-vitl"
