midas:
    model_path: "Intel/dpt-hybrid-midas"

depth_anything_v2:
    model_path: "depth-anything/Depth-Anything-V2-Large-hf"

depth_pro:
    # set to None to download from default url
    model_path:

lotus_depth:
    model_path: "jingheya/lotus-depth-g-v1-0"

lotus_normal:
    model_path: "jingheya/lotus-normal-g-v1-0"

dsine:
    # set to None to download from default url
    model_path:
    efficientnet_path:

upernet:
    model_path: openmmlab/upernet-convnext-large
