midas:
    model_path: "Intel/dpt-hybrid-midas"

depth_anything_v2:
    model_path: "depth-anything/Depth-Anything-V2-Large-hf"

dsine:
    # set to None to download from default url
    model_path:
    efficientnet_path:

upernet:
    model_path: openmmlab/upernet-convnext-large
