defaults:
  - datasets
  - models
  - _self_

verbose: false
device: cuda # cpu, cuda

input: examples/data/scannetpp_6b40d1a939_*.JPG
output: outputs/reconstruction.pth

multiview_reconstruction:
  method: dust3r
  image_list: ${input}
  export_point_cloud: true
  export_mesh: false

visualization:
  interactive: false
  method: pyrender
